name: Nkeep
version: 1.0.0
api:[1.0.0]
author: anjing
main: Nkeep\Main
descriprtion: "自定义死亡物品不掉落和死亡经验不掉落"
 
commands:
 keepinventory:
  description: 死亡物品掉落设置
  permission: op
 keepexperience:
  description: 死亡经验掉落设置
  permission: op
